apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dvzi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dvzi
    app.kubernetes.io/part-of: cin4s-839-0015-app
  name: devfile-sample-dvzi
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-dvzi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-dvzi
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0015-tenant/cin4s-839-0015-app/devfile-sample-dvzi@sha256:7865a5b258884d5c5ce1318cc73bcee7d082d59e3c903de2881f69684c2d52d9
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
