apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-dvzi
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0015-tenant/cin4s-839-0015-app/devfile-sample-dvzi@sha256:7865a5b258884d5c5ce1318cc73bcee7d082d59e3c903de2881f69684c2d52d9
        name: my-nodejs
        resources: {}
status: {}
